version: '3.4'
services:
  api:
    build: '.'
    container_name: test-nest-api
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./src:/usr/app/src
      - ./.env:/usr/app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: test-nest-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
